variables:
    PLATFORMS: linux/arm/v7,linux/arm64/v8,linux/386,linux/amd64
    BUILDX_MAX_PARALLELISM: 4

include: https://gitlab.com/Lukas1818/gitlab-ci-template-docker/-/raw/main/Docker.gitlab-ci.yml
